config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "people#list"

  get "/frequency", to: "people#frequency"
  get "/duplicates", to: "people#duplicates"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :initialize_salessoft_client

  def list
    @people = @client.people[:data]
  end

  def frequency
    @data = SalesLoft::PeopleService.frequency_count(@client.people[:data])
  end

  def duplicates
    @data = SalesLoft::PeopleService.find_duplicates(@client.people[:data])
  end

  private

  def initialize_salessoft_client
    @client = SalesLoft::Client.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SalesLoft Client
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body{:role => "main"}
    = yield
    = render partial: "people/navigation"

app/views/people/_navigation.html.haml
= react_component("Navigator", { listUrl: root_path, frequencyUrl: frequency_path, duplicatesUrl: duplicates_path })

app/views/people/duplicates.html.haml
= react_component("DuplicatesList", { data: @data })

app/views/people/frequency.html.haml
= react_component("FrequencyList", { data: @data })

app/views/people/index.html.haml
= react_component("PeopleList", { people: @people })
= render partial: "navigation"

app/views/people/list.html.haml
= react_component("PeopleList", { people: @people })